package com.kt.bdapportal.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.kt.bdapportal.domain.BdapCrypto;

public interface BdapCryptoRepository extends JpaRepository<BdapCrypto,String>{

	@Query(value="SELECT * FROM BDAP_CRYPTO WHERE CRT_OWNER_ID=?1 AND CRT_TYPE=?2 AND CRT_STATUS=?3", nativeQuery = true)
	public List<BdapCrypto> userDecTblAndCol(String userId, char crtType,String crtStatus);
		
	
	@Query(value="SELECT * FROM BDAP_CRYPTO WHERE CRT_OWNER_ID=?1 AND CRT_SRC_DB_NM=?2", nativeQuery = true)
	public List<BdapCrypto> tableManagementList(String userId, String dbNm);
	
	@Query(value="SELECT A.CRT_ID,A.CRT_TYPE,A.CRT_STATUS,A.CRT_PRJ_NM,A.CRT_REQ_REASON,A.CRT_REQ_DT,A.CRT_IS_CHK_RAW,A.CRT_START_DATE,A.CRT_END_DATE,A.CRT_RES_DT ,(SELECT GROUP_CONCAT(CRT_COL_NM SEPARATOR ',') FROM BDAP_CRYPTO_COL B WHERE A.CRT_ID=B.CRT_PARENT_ID) AS CRT_DOC_NUM,A.CRT_CREATE_TBL_NM,A.CRT_OWNER_ID,A.CRT_SRC_DB_NM,A.CRT_SRC_TBL_NM  FROM BDAP_CRYPTO A WHERE CRT_OWNER_ID=?1 AND CRT_TYPE=?2 ORDER BY CRT_REQ_DT DESC LIMIT ?3,?4 ", nativeQuery = true)
	public List<BdapCrypto> encDecList(String userId, char crtType,int startNum,int rows);
	
	@Query(value="SELECT A.CRT_ID,A.CRT_TYPE,A.CRT_STATUS,A.CRT_PRJ_NM,A.CRT_REQ_REASON,A.CRT_REQ_DT,A.CRT_IS_CHK_RAW,A.CRT_START_DATE,A.CRT_END_DATE,A.CRT_RES_DT ,(SELECT GROUP_CONCAT(CRT_COL_NM SEPARATOR ',') FROM BDAP_CRYPTO_COL B WHERE A.CRT_ID=B.CRT_PARENT_ID) AS CRT_DOC_NUM,A.CRT_CREATE_TBL_NM,A.CRT_OWNER_ID,A.CRT_SRC_DB_NM,A.CRT_SRC_TBL_NM  FROM BDAP_CRYPTO A WHERE CRT_TYPE=?1 LIMIT ?2,?3", nativeQuery = true)
	public List<BdapCrypto> encProcessList(char crtType,int startNum,int rows);
	
	
	@Query(value="SELECT A.CRT_ID,A.CRT_TYPE,A.CRT_STATUS,A.CRT_PRJ_NM,A.CRT_REQ_REASON,A.CRT_REQ_DT,A.CRT_IS_CHK_RAW,A.CRT_START_DATE,A.CRT_END_DATE,A.CRT_RES_DT ,(SELECT GROUP_CONCAT(CRT_COL_NM SEPARATOR ',') FROM BDAP_CRYPTO_COL B WHERE A.CRT_ID=B.CRT_PARENT_ID) AS CRT_DOC_NUM,A.CRT_CREATE_TBL_NM,A.CRT_OWNER_ID,A.CRT_SRC_DB_NM,A.CRT_SRC_TBL_NM  FROM BDAP_CRYPTO A WHERE CRT_TYPE=?1  AND CRT_STATUS=?2 LIMIT ?3,?4 ", nativeQuery = true)
	public List<BdapCrypto> decRoleList(char crtType,String crtStatus,int startNum,int rows);
	
	
	@Query(value="SELECT COUNT(*) CNT FROM (SELECT A.CRT_ID,A.CRT_TYPE,A.CRT_STATUS,A.CRT_PRJ_NM,A.CRT_REQ_REASON,A.CRT_REQ_DT,A.CRT_IS_CHK_RAW,A.CRT_START_DATE,A.CRT_END_DATE,A.CRT_RES_DT ,(SELECT GROUP_CONCAT(CRT_COL_NM SEPARATOR ',') FROM BDAP_CRYPTO_COL B WHERE A.CRT_ID=B.CRT_PARENT_ID) AS CRT_DOC_NUM,A.CRT_CREATE_TBL_NM,A.CRT_OWNER_ID,A.CRT_SRC_DB_NM,A.CRT_SRC_TBL_NM  FROM BDAP_CRYPTO A WHERE CRT_TYPE=?1 ) CNT", nativeQuery = true)
	public Long encProcessListCount(char crtType);
	
	
	@Query(value="SELECT COUNT(*) CNT FROM (SELECT A.CRT_ID,A.CRT_TYPE,A.CRT_STATUS,A.CRT_PRJ_NM,A.CRT_REQ_REASON,A.CRT_REQ_DT,A.CRT_IS_CHK_RAW,A.CRT_START_DATE,A.CRT_END_DATE,A.CRT_RES_DT ,(SELECT GROUP_CONCAT(CRT_COL_NM SEPARATOR ',') FROM BDAP_CRYPTO_COL B WHERE A.CRT_ID=B.CRT_PARENT_ID) AS CRT_DOC_NUM,A.CRT_CREATE_TBL_NM,A.CRT_OWNER_ID,A.CRT_SRC_DB_NM,A.CRT_SRC_TBL_NM  FROM BDAP_CRYPTO A WHERE CRT_TYPE=?1  AND CRT_STATUS=?2 ) CNT ", nativeQuery = true)
	public Long decRoleListCount(char crtType,String crtStatus);
	
	@Query(value="SELECT COUNT(*) CNT FROM (SELECT A.CRT_ID,A.CRT_TYPE,A.CRT_STATUS,A.CRT_PRJ_NM,A.CRT_REQ_REASON,A.CRT_REQ_DT,A.CRT_IS_CHK_RAW,A.CRT_START_DATE,A.CRT_END_DATE,A.CRT_RES_DT ,(SELECT GROUP_CONCAT(CRT_COL_NM SEPARATOR ',') FROM BDAP_CRYPTO_COL B WHERE A.CRT_ID=B.CRT_PARENT_ID) AS CRT_DOC_NUM,A.CRT_CREATE_TBL_NM,A.CRT_OWNER_ID,A.CRT_SRC_DB_NM,A.CRT_SRC_TBL_NM  FROM BDAP_CRYPTO A WHERE CRT_OWNER_ID=?1 AND CRT_TYPE=?2 ) CNT ", nativeQuery = true)
	public Long encDecListCount(String userId,char crtType);
	
	
	@Query(value="SELECT * FROM BDAP_CRYPTO WHERE CRT_ID=?1", nativeQuery = true)
	public BdapCrypto getBdapCryptoByCryptoId(String id);
	
	
	
	
	
	
}
